#!/bin/dash


. tigger-utilities


! [ $# -ne 0 ] || or_die "usage: $0 "



if [ -d '.tigger' ] 
then
	echo "$0: error: .tigger already exists" 1>&2
	exit 1
fi 


mkdir -- '.tigger'

echo "Initialized empty tigger repository in .tigger"