#!/bin/dash


. tigger-utilities



[ $# -ne 0 ] && die "usage: $TGGR"



[ -d '.tigger' ] && die "$TGGR: error: .tigger already exists"


#initialise the repo if it doesnt exist.
if [ ! -d "$REPO" ]
then
	mkdir -- "$REPO"                      || die "$TGGR: error: unable to create .tigger"
	mkdir -- "$REPO/commit"               || die "$TGGR: error: unable to create commit"
	mkdir -- "$REPO/index"                || die "$TGGR: error: unable to create index"
	mkdir -- "$REPO/heads"                || die "$TGGR: error: unable to create heads"
	echo -n "NULL" > "$REPO/heads/master" || die "$TGGR: error: unable to create master branch"
	echo -n "master" > "$REPO/HEAD"       || die "$TGGR: error: unable to create HEAD"
	touch  "$REPO/.log"                   || die "$TGGR: error: unable to create .log"

	
	echo "Initialized empty tigger repository in .tigger"
	exit 0

else
	die "$TGGR: error: .tigger already exists" 
fi

