#!/bin/dash

  #################
 #    Defines    #
#################


PWD=$(pwd)
REPO="$PWD/.tigger"
INDEX_DIR="$REPO/index"
TGGR=$(basename $0)




  #################
 #   Functions   #
#################


#emulate perls die function
die()
{
	err_msg="$1"
	echo "$err_msg" 1>&2
	exit 1
}
