#!/bin/dash


. tigger-utilities
. tigger-file_state
check_repo_exists


  #################
 #     Main      #
#################

# should never have 0 arguments
[ "$#" -ne 0 ]  || die "$PRGRM: usage: $PRGRM <filename>" 


#add all files in arguments 
for file in "$@"
do

	# 'Adding' a removed file
	status=$(find_files_state "$file" 'HEAD')
  if [ "$status" = "$INDEX_ONLY" ]  || [ "$status" =  "$REP_AND_IND" ]      
  then
    tigger-rm --cached --force "$file"
    continue
  fi



	[ $(echo "$file" | grep -E "^\.") ] 	&& die "$PRGRM: error: invalid filename '$file'"

	[ -e "$file" ]                        || die "$PRGRM: error: can not open '$file'"
	[ -f "$file" ]                        || die "$PRGRM: error: '$file' is not a regular file"
	cp -a -- "$file" "$REPO/index"        || die "$PRGRM: error: unable to copy $file"
 
done



