#!/bin/dash


. tigger-utilities
check_repo_exists



[ $# -eq 0 ] || die "usage: $PRGRM"


branch="$(find_head)"
#display log belonging to current commit
[ -f  "$REPO/logs/$branch" ] && cat "$REPO/logs/$branch"

exit 0


