#!/bin/dash


. tigger-utilities
. tigger-file_state
check_repo_exists

  #################
 #    Defines    #
#################


CACHED_OPT=$FALSE
FORCE_OPT=$FALSE

STAGED_CHANGES_1=$IND_AND_PWD
STAGED_CHANGES_2=$DELTA_REP_IND_DELTA_REP_PWD
REPO_DIFF_TO_WRKING_FILE=$DELTA_IND_PWD_DELTA_REP_PWD
IND_DIFF_WRK_REPO=$DELTA_REP_IND_DELTA_IND_PWD

  #################
 #   Functions   #
#################

#deletes without checking file status's.
# if --cached option used only deletes from index
# otherwise files in pwd and index are deleted.
force_delete()
{
	CACHED_OPT="$1"

	for file in "$@"
  	do
	    if [ $CACHED_OPT -eq $TRUE ] 
	    then
	      rm -f "$REPO/index/$file" 2> /dev/null
	    else
	      rm -f "$REPO/index/$file" "$PWD/$file" 2> /dev/null
	    fi
  	done
}



  #################
 #     Main      #
#################

#convert long options to short options for getopts
for arg in "$@"; do
  shift
  case "$arg" in
    '--cached') set -- "$@" '-c'   ;;
    '--force')  set -- "$@" '-f'   ;;
    *)          set -- "$@" "$arg" ;;
  esac
done


while getopts ':cf' opts
do
	case "$opts" in
		c) CACHED_OPT=$TRUE;;
		f) FORCE_OPT=$TRUE;;
		\?) die "usage: $PRGRM [--force] [--cached] <filenames>"
	esac
done
shift "$(($OPTIND - 1))"


#ensure file name given
[ $# -ne 0 ] || die "usage: $PRGRM [--force] [--cached] <filenames>"


#make sure all files exist in the index before proceeding
for file in "$@"
do
  is_file_in_index "$file" || die "$PRGRM: error: '$file' is not in the tigger repository"
done


#if forced is active then no error checking 
if [ $FORCE_OPT -eq $TRUE ]
then

  force_delete $CACHED_OPT

elif [ $CACHED_OPT -eq $FALSE ]
then

	for file in "$@"
	do

		status=$(find_files_state "$file" 'HEAD')

		[ "$status" = "$STAGED_CHANGES_1" ]      && die "$PRGRM: error: '$file' has staged changes in the index"
		[ "$status" = "$STAGED_CHANGES_2" ]      && die "$PRGRM: error: '$file' has staged changes in the index"
		[ "$status" = "$REPO_DIFF_WRKING_FILE" ] && die "$PRGRM: error: '$file' in the repository is different to the working file"  
		[ "$status" = "$IND_DIFF_WRK_REPO" ]     && die "$PRGRM: error: '$file' in index is different to both to the working file and the repository"  

	done


fi
















