#!/bin/dash



. tigger-utilities
. tigger-file_state
check_repo_exists



trap "rm  -f $list" EXIT INT




  #################
 #    Defines    #
#################


COMMIT_DIR="$REPO/commit/$("find_where_head_points")"


#File error for given status
PWD_ONLY="$D3_ONLY"
INDEX_ONLY="$D2_ONLY"  
IND_AND_PWD="$D2_AND_D3"
DELTA_IND_PWD="$DELTA_D2_D3"
REP_ONLY="$D1_ONLY"   
REP_AND_PWD="$D1_AND_D3"  
DELTA_REP_PWD="$DELTA_D1_D3"   
REP_AND_IND="$D1_AND_D2" 
DELTA_REP_IND="$DELTA_D1_D2" 
DELTA_IND_PWD_DELTA_REP_PWD="$DELTA_D2_D3_DELTA_D1_D3" 
DELTA_REP_IND_DELTA_REP_PWD="$DELTA_D1_D2_DELTA_D1_D3"
DELTA_REP_IND_DELTA_IND_PWD="$DELTA_D1_D2_DELTA_D2_D3"


  #################
 #     Main      #
#################


for file in $(basename --multiple "$COMMIT_DIR"/* "$INDEX_DIR"/* "$PWD"/* |sort|uniq|sed '/*/d' |xargs)
do
  
  status=$(find_files_state "$file" "$COMMIT_DIR" "$INDEX_DIR" "$PWD")

  [ "$status" = "$PWD_ONLY" ]       && status_msg="untracked" 
  [ "$status" = "$DELTA_REP_PWD" ]  && status_msg="untracked"      
  [ "$status" = "$REP_AND_PWD" ]    && status_msg="untracked"                                       
  [ "$status" = "$ALL_SAME" ]       && status_msg="same as repo"                                      
  [ "$status" = "$REP_AND_IND" ]    && status_msg="file deleted"                                      
  [ "$status" = "$REP_ONLY" ]       && status_msg="deleted"                                           
  [ "$status" = "$IND_AND_PWD" ]    && status_msg="added to index" 
  [ "$status" = "$INDEX_ONLY" ]     && status_msg="added to index, file deleted"
  [ "$status" = "$DELTA_IND_PWD" ]  && status_msg="added to index, file changed"                                
  [ "$status" = "$ALL_DIFFERENT" ]               && status_msg="file changed, different changes staged for commit"
  [ "$status" = "$DELTA_REP_IND_DELTA_IND_PWD" ] && status_msg="file changed, different changes staged for commit" 
  [ "$status" = "$DELTA_REP_IND_DELTA_REP_PWD" ] && status_msg="file changed, changes staged for commit"        
  [ "$status" = "$DELTA_IND_PWD_DELTA_REP_PWD" ] && status_msg="file changed, changes not staged for commit"    
  [ "$status" = "$DELTA_REP_IND" ]               && status_msg="file deleted, different changes staged for commit" 

  echo "$file - $status_msg"

done

exit 0




